---
abstract: 'the uniform way to use curl, wget, LWP, HTTP::Lite, etc.'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plient
resources:
  repository: http://github.com/bestpractical/plient.git
version: 0.01
